[general]
live_config_reload = true
working_directory = "C:\\Users\\zxcf"

[terminal]
shell = "C:\\others\\program\\Git\\bin\\bash.exe"

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#F8BD96"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#988BA2"
blue = "#96CDFB"
cyan = "#89DCEB"
green = "#ABE9B3"
magenta = "#F5C2E7"
red = "#F28FAD"
white = "#D9E0EE"
yellow = "#FAE3B0"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1D2F"

[colors.normal]
black = "#6E6C7E"
blue = "#96CDFB"
cyan = "#89DCEB"
green = "#ABE9B3"
magenta = "#F5C2E7"
red = "#F28FAD"
white = "#D9E0EE"
yellow = "#FAE3B0"

[colors.primary]
background = "#1E1D2F"
foreground = "#D9E0EE"

[cursor.style]
blinking = "off"
shape = "Block"

[font]
size = 14.0

[font.bold]
family = "Maple Mono NF CN"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF CN"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF CN"
style = "Italic"

[font.normal]
family = "Maple Mono NF CN"
style = "Regular"

[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u007F\\s\"<>\\\\^⟨⟩`-]+"

[hints.enabled.mouse]
enabled = true
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Insert"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[[mouse.bindings]]
action = "Paste"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "Paste"
mouse = "Middle"

[[mouse.bindings]]
action = "PasteSelection"
mods = "Control"
mouse = "Middle"

[scrolling]
history = 1000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t@="


[window]
decorations = "full"
dynamic_title = true
opacity = 1
startup_mode = "Maximized"
title = "Alacritty"
